"""Read JSON schema files from the schemas directory or Compass schema file."""

import json
import logging
import os
from pathlib import Path

from mockdata.utils import bold, cyan, green

logger = logging.getLogger(__name__)


def read_schemas(schemas_path: Path) -> dict:
    """Read all JSON schema files from the schemas directory.

    Returns:
        Dictionary with filenames as keys and schema content as values.
    """
    logger.info(cyan("Reading schema definition files from the schemas directory."))
    schemas = {}

    for filename in os.listdir(schemas_path):
        if filename.endswith(".json"):
            file_path = schemas_path / filename
            logger.info("Loading: %s", cyan(filename))
            with open(file_path, "r", encoding="utf-8") as file:
                content = json.load(file)
                schema_name = content.get(
                    "name", filename[:-5]
                )  # Use filename without .json as name
                schemas[schema_name] = content

    logger.info(bold(green(f"{len(schemas)} schemas loaded successfully.")))
    return schemas


def read_compass_schema(compass_schema_path: Path):
    """Read a JSON schema file generated by Compass.

    Args:
        compass_schema_path: Path to the Compass-generated JSON schema file.

    Returns:
        Dictionary containing the schema content.
    """
    logger.info(cyan("Reading schema definition from Compass-generated JSON file."))
    with open(compass_schema_path, "r", encoding="utf-8") as file:
        content = json.load(file)
        return content
