"""Command-line interface for mock data generator."""

import json
import sys
from argparse import ArgumentParser
from logging import getLogger
from pathlib import Path
from typing import Any

from mockdata.core.mock_data import MockData
from mockdata.core.read_schemas import read_compass_schema, read_schemas
from mockdata.providers import EJsonProvider, KafkaProvider, MongoDBProvider
from mockdata.utils import bold, cyan, green, red, yellow
from mockdata.utils.logging import init_logging
from mockdata.utils.simple_ai import DBPATH, SimpleAI


def show_progress(current: int, total: int) -> None:
    """Display progress indicator.

    Args:
        current: Current progress count.
        total: Total count for completion.
    """
    spinner = ["|", "/", "-", "\\"]
    percentage = round(current / total * 100, 2) if total > 0 else 0
    sys.stdout.write(f"\r{spinner[current % len(spinner)]} {percentage}%")
    sys.stdout.flush()


def parse_args() -> dict:
    """Parse command-line arguments.

    Returns:
        Dictionary of parsed arguments.
    """
    logger = getLogger(__name__)
    arg_parser = ArgumentParser(description="Mock data generator based on JSON schemas.")
    arg_parser.add_argument(
        "-s",
        "--schemas",
        type=str,
        default="schemas",
        help="Path to the directory containing JSON schema files, "
        + "or json schema file generated by Compass. (default: schemas)",
    )
    arg_parser.add_argument(
        "-t",
        "--output-type",
        type=str,
        default="ejson",
        help="Output type (default: ejson). Options: ejson, mongodb, kafka",
    )
    arg_parser.add_argument(
        "-n",
        "--num-objects",
        type=int,
        default=100,
        help="Number of objects to generate (default: 100)",
    )
    arg_parser.add_argument(
        "-r",
        "--refresh",
        action="store_true",
        help="Refresh the ChromaDB collection with Faker methods. Use this if you have updated Faker or added custom providers. Default: False",
    )
    arg_parser.add_argument(
        "target",
        nargs="?",
        help="Depending on the -t argument, specify folder for ejson, "
        + "connection string (mongodb:// or mongodb+srv://) for mongodb, "
        + "or bootstrap server for kafka",
    )
    # If schemas is a folder, we will read all JSON files in that folder.
    # If it's a single JSON file, we will read that file as compass exported schema.
    args = vars(arg_parser.parse_args())
    schemas_path: str = str(args.get("schemas"))
    if schemas_path.endswith(".json"):
        logger.info(
            cyan("Detected single JSON file for schemas. Assuming Compass exported schema format.")
        )
        # Check if the file exists
        if not Path(schemas_path).exists():
            logger.fatal(red(f"Schema file not found: {schemas_path}"))
            sys.exit(1)
        args["schemas_type"] = "compass"
    else:
        logger.info(cyan("Detected schemas directory. Reading all JSON files in the directory."))
        # Check if the directory exists
        if not Path(schemas_path).exists():
            logger.fatal(red(f"Schemas directory not found: {schemas_path}"))
            sys.exit(1)
        args["schemas_type"] = "directory"

    output_type: str = str(args.get("output_type")).lower()
    target: str = str(args.get("target"))
    if output_type not in ["ejson", "mongodb", "kafka"]:
        logger.fatal(
            red(
                f"Invalid output type specified: {output_type}. "
                + "Valid options are: ejson, mongodb, kafka."
            )
        )
        sys.exit(1)
    if output_type == "ejson":
        Path.cwd().joinpath(target).mkdir(parents=True, exist_ok=True)
    elif output_type == "mongodb":
        if not (target.startswith("mongodb://") or target.startswith("mongodb+srv://")):
            logger.fatal(
                red(
                    f"Invalid MongoDB connection string: {target}. "
                    + "It should start with mongodb:// or mongodb+srv://"
                )
            )
            sys.exit(1)
    elif output_type == "kafka":
        # For Kafka, we expect the target to be in the format of "bootstrap_servers: topic1,topic2"
        if ":" not in target:
            logger.fatal(
                red(
                    f"Invalid Kafka target format: {target}. "
                    + "It should be in the format 'bootstrap_servers: topic1,topic2'"
                )
            )
            sys.exit(1)
        bootstrap_servers, topics = target.split(":", 1)
        args["bootstrap_servers"] = bootstrap_servers.strip()
        args["topics"] = [topic.strip() for topic in topics.split(",")]
    return args


def main() -> None:
    """Main entry point for the CLI."""
    init_logging()
    logger = getLogger(__name__)
    args = parse_args()
    num_objects: int = args.get("num_objects", 100)
    output_type: str = str(args.get("output_type")).lower()
    schemas_type: str = str(args.get("schemas_type"))
    schemas: dict[str, Any]
    if schemas_type == "directory":
        # Read schemas from the specified directory
        schemas_path: str = str(args.get("schemas"))
        try:
            schemas = read_schemas(Path(schemas_path))
        except (FileNotFoundError, json.JSONDecodeError, PermissionError, OSError) as e:
            logger.fatal(red(f"Failed to read schemas from directory: {e}"))
            sys.exit(1)
        if not schemas:
            logger.error(
                red("No schemas found. Please add JSON schema files to the schemas directory.")
            )
            sys.exit(1)
    else:
        # Read schema from the specified Compass-generated JSON file
        compass_schema_path: str = str(args.get("schemas"))
        try:
            schemas = read_compass_schema(Path(compass_schema_path))
        except (FileNotFoundError, json.JSONDecodeError, PermissionError, OSError) as e:
            logger.fatal(red(f"Failed to read schema from Compass JSON file: {e}"))
            sys.exit(1)

    refresh: bool = args.get("refresh", False)
    if refresh:
        logger.info(yellow("Refreshing ChromaDB collection with Faker methods..."))
        SimpleAI.refresh_methods()

    try:
        logger.info(cyan("Mocking data based on the provided schemas."))
        target: str = str(args.get("target"))
        collections: dict[str, Any] = schemas.get("collections", {})
        for _, schema in collections.items():
            mock_data = MockData(schema, num_objects)
            if output_type == "ejson":
                mock_data.add_output_provider(EJsonProvider({"folder": target}))
            elif output_type == "mongodb":
                mock_data.add_output_provider(MongoDBProvider({"uri": target, "batch_size": 1000}))
            elif output_type == "kafka":
                mock_data.add_output_provider(KafkaProvider({"bootstrap_servers": target}))

            processed_count = 0
            for _ in mock_data.run():
                processed_count += 1
                show_progress(processed_count, mock_data.count)

            mock_data.close()

            # Clear progress line
            sys.stdout.write("\r")
            sys.stdout.flush()

            logger.info(
                bold(
                    green(
                        f"Successfully mocked {processed_count} objects "
                        + f"for schema: {schema['ns']}"
                    )
                )
            )
    except KeyboardInterrupt:
        logger.info("\nOperation cancelled by user.")
        sys.exit(1)


if __name__ == "__main__":
    main()
